#!/usr/bin/env python3
"""Loopback authorization rewriter and Codex compaction compatibility proxy.

Ordinary HTTP/SSE and WebSocket traffic is forwarded to CLIProxyAPI. Only
Responses JSON requests that contain compaction state are decoded. Synthetic
summaries are generated by the currently selected model and are never logged.
"""

from __future__ import annotations

import json
import os
from pathlib import Path
import selectors
import socket
import socketserver
import subprocess
import sys
import threading
import time
from typing import Iterable
import urllib.error
import urllib.request


SCRIPT_DIR = Path(__file__).resolve().parent
if str(SCRIPT_DIR) not in sys.path:
    sys.path.insert(0, str(SCRIPT_DIR))

from compaction import (  # noqa: E402
    CompactionError,
    MAX_COMPACTION_BODY_BYTES,
    build_summary_payload,
    build_v1_output,
    build_v2_failure_events,
    build_v2_response,
    decode_request_body,
    encode_request_body,
    encoding_supported,
    extract_output_text,
    is_native_compaction_model,
    is_v2_compaction_request,
    prepare_forward_payload,
    render_sse,
)


LISTEN_HOST = "127.0.0.1"
LISTEN_PORT = int(os.environ.get("CODEX_BRIDGE_LISTEN_PORT", "8318"))
UPSTREAM_HOST = "127.0.0.1"
UPSTREAM_PORT = int(os.environ.get("CODEX_BRIDGE_UPSTREAM_PORT", "8317"))
MAX_HEADER_BYTES = 64 * 1024
MAX_RESPONSE_BYTES = 16 * 1024 * 1024
MAX_FORWARD_BODY_BYTES = 128 * 1024 * 1024
SUMMARY_TIMEOUT = int(os.environ.get("CODEX_BRIDGE_COMPACTION_TIMEOUT", "180"))
SUMMARY_ATTEMPTS = int(os.environ.get("CODEX_BRIDGE_COMPACTION_ATTEMPTS", "3"))
PROTOCOL_VERSION = "2"


class ProxyStats:
    def __init__(self) -> None:
        self._lock = threading.Lock()
        self._values = {
            "v1_requests": 0,
            "v2_native_requests": 0,
            "v2_synthetic_requests": 0,
            "replay_decodes": 0,
            "reasoning_items_cleaned": 0,
            "successes": 0,
            "failures": 0,
        }
        self._last_error_type: str | None = None

    def add(self, key: str, amount: int = 1) -> None:
        with self._lock:
            self._values[key] = self._values.get(key, 0) + amount

    def success(self) -> None:
        self.add("successes")

    def failure(self, error_type: str) -> None:
        with self._lock:
            self._values["failures"] += 1
            self._last_error_type = error_type

    def snapshot(self) -> dict:
        with self._lock:
            return {
                "protocol_version": PROTOCOL_VERSION,
                **self._values,
                "last_error_type": self._last_error_type,
            }


STATS = ProxyStats()


class SummaryError(RuntimeError):
    pass


def helper_command() -> list[str]:
    command = os.environ.get("CODEX_BRIDGE_HELPER_CMD")
    helper = os.environ.get("CODEX_BRIDGE_HELPER")
    if not command or not helper:
        raise RuntimeError("credential helper is not configured")
    raw_args = os.environ.get("CODEX_BRIDGE_HELPER_ARGS", "[]")
    try:
        args = json.loads(raw_args)
    except json.JSONDecodeError as exc:
        raise RuntimeError("credential helper arguments are invalid") from exc
    if not isinstance(args, list) or not all(isinstance(item, str) for item in args):
        raise RuntimeError("credential helper arguments must be a string array")
    return [command, *args, helper]


def read_client_key() -> str:
    proc = subprocess.run(
        helper_command(),
        stdin=subprocess.DEVNULL,
        stdout=subprocess.PIPE,
        stderr=subprocess.DEVNULL,
        text=True,
        timeout=5,
        check=False,
    )
    key = proc.stdout.strip()
    if proc.returncode != 0 or not key:
        raise RuntimeError("credential helper returned no key")
    return key


def receive_headers(client: socket.socket) -> tuple[bytes, bytes]:
    data = bytearray()
    while b"\r\n\r\n" not in data:
        chunk = client.recv(8192)
        if not chunk:
            raise ConnectionError("client closed before sending headers")
        data.extend(chunk)
        if len(data) > MAX_HEADER_BYTES:
            raise ValueError("request headers are too large")
    marker = data.index(b"\r\n\r\n") + 4
    return bytes(data[:marker]), bytes(data[marker:])


def parse_request(header: bytes) -> tuple[str, list[tuple[str, str]]]:
    lines = header.decode("iso-8859-1").split("\r\n")
    request_line = lines[0]
    headers: list[tuple[str, str]] = []
    for line in lines[1:]:
        if not line:
            continue
        if ":" not in line:
            raise ValueError("malformed HTTP header")
        name, value = line.split(":", 1)
        headers.append((name.strip(), value.strip()))
    return request_line, headers


def request_parts(request_line: str) -> tuple[str, str]:
    parts = request_line.split()
    if len(parts) < 2:
        raise ValueError("malformed HTTP request line")
    return parts[0].upper(), parts[1].split("?", 1)[0]


def header_value(headers: Iterable[tuple[str, str]], name: str) -> str | None:
    lowered = name.lower()
    for key, value in headers:
        if key.lower() == lowered:
            return value
    return None


def is_health_request(request_line: str) -> bool:
    _method, path = request_parts(request_line)
    return path == "/__codex_bridge_health"


def is_upgrade(headers: Iterable[tuple[str, str]]) -> bool:
    return any(name.lower() == "upgrade" and value for name, value in headers)


def is_responses_path(path: str) -> bool:
    return path == "/responses" or path.endswith("/responses")


def is_legacy_compaction_path(path: str) -> bool:
    return path == "/responses/compact" or path.endswith("/responses/compact")


def receive_body(client: socket.socket, remainder: bytes, headers: list[tuple[str, str]]) -> bytes | None:
    raw_length = header_value(headers, "content-length")
    if raw_length is None:
        return None
    try:
        length = int(raw_length)
    except ValueError as exc:
        raise CompactionError("invalid Content-Length") from exc
    if length < 0 or length > MAX_FORWARD_BODY_BYTES:
        raise CompactionError("request body exceeds forwarding limit")
    data = bytearray(remainder[:length])
    while len(data) < length:
        chunk = client.recv(min(64 * 1024, length - len(data)))
        if not chunk:
            raise CompactionError("client closed before request body completed")
        data.extend(chunk)
    return bytes(data)


def rewritten_request(
    request_line: str,
    headers: list[tuple[str, str]],
    key: str,
    body_length: int | None = None,
) -> bytes:
    upgraded = is_upgrade(headers)
    rendered: list[tuple[str, str]] = []
    saw_auth = False
    saw_connection = False
    saw_length = False
    for name, value in headers:
        lowered = name.lower()
        if lowered == "authorization":
            rendered.append((name, f"Bearer {key}"))
            saw_auth = True
        elif lowered == "host":
            rendered.append((name, f"{UPSTREAM_HOST}:{UPSTREAM_PORT}"))
        elif lowered == "connection" and not upgraded:
            rendered.append((name, "close"))
            saw_connection = True
        elif lowered == "content-length" and body_length is not None:
            rendered.append((name, str(body_length)))
            saw_length = True
        elif lowered == "transfer-encoding" and body_length is not None:
            continue
        else:
            rendered.append((name, value))
    if not saw_auth:
        rendered.append(("Authorization", f"Bearer {key}"))
    if body_length is not None and not saw_length:
        rendered.append(("Content-Length", str(body_length)))
    if not upgraded and not saw_connection:
        rendered.append(("Connection", "close"))
    lines = [request_line, *(f"{name}: {value}" for name, value in rendered), "", ""]
    return "\r\n".join(lines).encode("iso-8859-1")


def send_response(client: socket.socket, status: int, reason: str, body: bytes, content_type: str) -> None:
    response = (
        f"HTTP/1.1 {status} {reason}\r\n".encode()
        + f"Content-Type: {content_type}\r\n".encode()
        + f"Content-Length: {len(body)}\r\n".encode()
        + b"Cache-Control: no-store\r\nConnection: close\r\n\r\n"
        + body
    )
    client.sendall(response)


def send_json(client: socket.socket, payload: object, status: int = 200, reason: str = "OK") -> None:
    body = json.dumps(payload, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    send_response(client, status, reason, body, "application/json")


def send_health(client: socket.socket) -> None:
    send_json(
        client,
        {
            "status": "ok",
            "upstream": f"{UPSTREAM_HOST}:{UPSTREAM_PORT}",
            "compaction": STATS.snapshot(),
        },
    )


def send_error(client: socket.socket, status: int = 502, error_type: str = "proxy_unavailable") -> None:
    reasons = {400: "Bad Request", 411: "Length Required", 413: "Payload Too Large", 415: "Unsupported Media Type", 502: "Bad Gateway"}
    try:
        send_json(
            client,
            {"error": {"type": error_type, "message": "Codex bridge could not process this request."}},
            status=status,
            reason=reasons.get(status, "Error"),
        )
    except OSError:
        pass


def _extract_sse_response(payload: bytes) -> dict | None:
    completed: dict | None = None
    for raw in payload.splitlines():
        if not raw.startswith(b"data:"):
            continue
        value = raw[5:].strip()
        if not value or value == b"[DONE]":
            continue
        try:
            event = json.loads(value)
        except json.JSONDecodeError:
            continue
        if isinstance(event, dict) and event.get("type") == "response.completed" and isinstance(event.get("response"), dict):
            completed = event["response"]
    return completed


def request_summary(key: str, payload: dict) -> str:
    request_body = json.dumps(build_summary_payload(payload), ensure_ascii=False, separators=(",", ":")).encode("utf-8")
    request = urllib.request.Request(
        f"http://{UPSTREAM_HOST}:{UPSTREAM_PORT}/v1/responses",
        data=request_body,
        headers={
            "Authorization": f"Bearer {key}",
            "Content-Type": "application/json",
            "Accept": "application/json",
            "Accept-Encoding": "identity",
        },
        method="POST",
    )
    raw = b""
    content_type = ""
    status = 0
    last_error: SummaryError | None = None
    for attempt in range(max(1, SUMMARY_ATTEMPTS)):
        try:
            with urllib.request.urlopen(request, timeout=SUMMARY_TIMEOUT) as response:
                raw = response.read(MAX_RESPONSE_BYTES + 1)
                content_type = response.headers.get("Content-Type", "")
                status = response.status
            last_error = None
            break
        except urllib.error.HTTPError as exc:
            last_error = SummaryError(f"upstream_http_{exc.code}")
            if exc.code not in {429, 500, 502, 503, 504}:
                raise last_error from exc
        except (OSError, TimeoutError) as exc:
            last_error = SummaryError(type(exc).__name__)
        if attempt + 1 < max(1, SUMMARY_ATTEMPTS):
            time.sleep(min(2.0, 0.25 * (2**attempt)))
    if last_error is not None:
        raise last_error
    if status < 200 or status >= 300:
        raise SummaryError(f"upstream_http_{status}")
    if len(raw) > MAX_RESPONSE_BYTES:
        raise SummaryError("upstream_response_too_large")
    try:
        if "text/event-stream" in content_type:
            parsed = _extract_sse_response(raw)
        else:
            parsed = json.loads(raw)
    except (UnicodeDecodeError, json.JSONDecodeError) as exc:
        raise SummaryError("invalid_upstream_json") from exc
    summary = extract_output_text(parsed)
    if not summary:
        raise SummaryError("empty_summary")
    return summary


def send_v2_failure(client: socket.socket, model: str, stream: bool, error_type: str) -> None:
    if stream:
        body = render_sse(build_v2_failure_events(model, error_type))
        send_response(client, 200, "OK", body, "text/event-stream")
    else:
        send_error(client, 502, error_type)


def tunnel(left: socket.socket, right: socket.socket) -> None:
    selector = selectors.DefaultSelector()
    selector.register(left, selectors.EVENT_READ, right)
    selector.register(right, selectors.EVENT_READ, left)
    try:
        while selector.get_map():
            for key, _ in selector.select(timeout=60):
                source = key.fileobj
                target = key.data
                try:
                    chunk = source.recv(64 * 1024)
                except OSError:
                    chunk = b""
                if not chunk:
                    try:
                        selector.unregister(source)
                    except Exception:
                        pass
                    try:
                        target.shutdown(socket.SHUT_WR)
                    except OSError:
                        pass
                    continue
                target.sendall(chunk)
    finally:
        selector.close()


class ProxyHandler(socketserver.BaseRequestHandler):
    def handle(self) -> None:
        client: socket.socket = self.request
        upstream: socket.socket | None = None
        try:
            header, remainder = receive_headers(client)
            request_line, headers = parse_request(header)
            if is_health_request(request_line):
                send_health(client)
                return
            key = read_client_key()
            method, path = request_parts(request_line)
            managed_path = method == "POST" and (is_responses_path(path) or is_legacy_compaction_path(path))
            if not managed_path or is_upgrade(headers):
                upstream = socket.create_connection((UPSTREAM_HOST, UPSTREAM_PORT), timeout=10)
                upstream.settimeout(None)
                client.settimeout(None)
                upstream.sendall(rewritten_request(request_line, headers, key) + remainder)
                tunnel(client, upstream)
                return

            body = receive_body(client, remainder, headers)
            if body is None:
                if is_legacy_compaction_path(path):
                    send_error(client, 411, "content_length_required")
                    return
                upstream = socket.create_connection((UPSTREAM_HOST, UPSTREAM_PORT), timeout=10)
                upstream.settimeout(None)
                client.settimeout(None)
                upstream.sendall(rewritten_request(request_line, headers, key) + remainder)
                tunnel(client, upstream)
                return

            encoding = header_value(headers, "content-encoding") or "identity"
            if not encoding_supported(encoding):
                # Never reject traffic just because we cannot parse it: tunnel
                # the untouched body through, like the previous Node proxy did.
                STATS.add("unsupported_encoding_bypasses")
                upstream = socket.create_connection((UPSTREAM_HOST, UPSTREAM_PORT), timeout=10)
                upstream.settimeout(None)
                client.settimeout(None)
                upstream.sendall(rewritten_request(request_line, headers, key, len(body)) + body)
                tunnel(client, upstream)
                return
            decoded = decode_request_body(body, encoding, max_bytes=MAX_FORWARD_BODY_BYTES)
            try:
                payload = json.loads(decoded)
            except (UnicodeDecodeError, json.JSONDecodeError):
                send_error(client, 400, "invalid_json")
                return
            if not isinstance(payload, dict):
                send_error(client, 400, "invalid_json_root")
                return

            model = payload.get("model") if isinstance(payload.get("model"), str) else "unknown"
            stream = payload.get("stream") is True
            if (is_legacy_compaction_path(path) or is_v2_compaction_request(payload)) and len(decoded) > MAX_COMPACTION_BODY_BYTES:
                raise CompactionError("request body exceeds 32 MiB after decoding")
            if is_legacy_compaction_path(path):
                STATS.add("v1_requests")
                try:
                    summary = request_summary(key, payload)
                    output = build_v1_output(payload.get("input"), summary)
                    send_json(client, {"output": output})
                    STATS.success()
                except (CompactionError, SummaryError) as exc:
                    STATS.failure(type(exc).__name__ if not str(exc) else str(exc))
                    send_error(client, 502, "compaction_failed")
                return

            if is_v2_compaction_request(payload) and not is_native_compaction_model(model):
                STATS.add("v2_synthetic_requests")
                try:
                    summary = request_summary(key, payload)
                    response, events = build_v2_response(model, summary)
                    if stream:
                        send_response(client, 200, "OK", render_sse(events), "text/event-stream")
                    else:
                        send_json(client, response)
                    STATS.success()
                except (CompactionError, SummaryError) as exc:
                    error_type = type(exc).__name__ if not str(exc) else str(exc)
                    STATS.failure(error_type)
                    send_v2_failure(client, model, stream, "compaction_failed")
                return

            updated, changes = prepare_forward_payload(payload)
            if is_v2_compaction_request(payload):
                STATS.add("v2_native_requests")
            STATS.add("replay_decodes", changes["decoded_compactions"])
            STATS.add("reasoning_items_cleaned", changes["reasoning_items_cleaned"])
            if any(changes.values()):
                rendered = json.dumps(updated, ensure_ascii=False, separators=(",", ":")).encode("utf-8")
                body = encode_request_body(rendered, encoding)

            upstream = socket.create_connection((UPSTREAM_HOST, UPSTREAM_PORT), timeout=10)
            upstream.settimeout(None)
            client.settimeout(None)
            upstream.sendall(rewritten_request(request_line, headers, key, len(body)) + body)
            tunnel(client, upstream)
        except CompactionError as exc:
            STATS.failure(type(exc).__name__ if not str(exc) else str(exc))
            status = 413 if "limit" in str(exc) or "32 MiB" in str(exc) else 415 if "encoding" in str(exc) else 400
            send_error(client, status, "compaction_request_rejected")
        except Exception as exc:
            STATS.failure(type(exc).__name__)
            send_error(client)
        finally:
            if upstream is not None:
                try:
                    upstream.close()
                except OSError:
                    pass


class ThreadingLoopbackServer(socketserver.ThreadingTCPServer):
    allow_reuse_address = True
    daemon_threads = True


def main() -> None:
    with ThreadingLoopbackServer((LISTEN_HOST, LISTEN_PORT), ProxyHandler) as server:
        server.serve_forever(poll_interval=0.25)


if __name__ == "__main__":
    try:
        main()
    except KeyboardInterrupt:
        sys.exit(0)
